### ISSUE TITLE
Dados mais atuais

### ISSUE THREAD

**Issue by turicas** [endoedgar/covid19-monitorbr#1]
Você pode fazer a aplicação acessar a API diretamente para ter os dados mais atuais:
- https://brasil.io/api/dataset/covid19/caso/boletim
- https://brasil.io/api/dataset/covid19/caso/data

Dicas de uso da API:
- Você pode passar pra API os filtros que existem na interface via query string ([preencha o form de filtros na página do dataset e pegue a query string](https://brasil.io/dataset/covid19/caso))
- Você pode filtrar por `is_last=True` para ter os dados mais atuais de cada município/estado

Ou, caso queira, pode baixar os CSVs que mantenho online (são atualizados junto com os dados disponíveis na API):
    https://data.brasil.io/dataset/covid19/boletim.csv.gz
    https://data.brasil.io/dataset/covid19/caso.csv.gz

Lembrando que:

- As contagens estaduais podem ser diferentes das municipais, por dois motivos:
  1. Secretaria estadual parou de divulgar dados por município e está somente divulgando por estado (isso está acontecendo com SP);
  2. Secretaria estadual divulgou errado (às vezes acontece).
- Nem sempre nossos dados baterão com os do Ministério da Saúde, pois pode ser que nossa coleta seja feita depois da coleta do Ministério e, com isso, teremos dados mais atuais.

**Comment by endoedgar** [comment]
Olá, eu irei fazer essas mudanças hoje a noite e colocar esses avisos na tela inicial que você pediu.

No momento o app acessa a URL https://brasil.io/api/dataset/covid19 para exibir a data e dados da última atualização da tabela Casos.

Interessante sobre a query, vou implementar também!

Obrigado pelo feedback.

A tarde também vou aproveitar e lançar o código fonte para a galera poder cooperar neste projeto, pois estou meio sobrecarregado com atividades do mestrado.

**Comment by endoedgar** [comment]
Aviso já está la no Mapa.

**Comment by turicas** [comment]
Criamos uma [pequena documentação da API](http://github.com/turicas/covid19-br/tree/master/api.md) que talvez possa te ajudar.
